theme: jekyll-theme-minimal
title: Bruce Cheung
description: Bruce is a maker who likes to build things for fun. He is especially interested in chat systems, natural language understanding, and linguistics.
logo: /assets/img/ProfileCircular.png